apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-excalidraw-service
  namespace: excalidraw
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator
  namespace: excalidraw
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator-binding
subjects:
- kind: ServiceAccount
  name: my-excalidraw-service
  namespace: excalidraw
roleRef:
  kind: Role
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io
